---
kind: pipeline
type: exec
name: push

platform:
  os: linux
  arch: amd64

steps:
#   - name: lint
#     commands:
#       - make lint
  - name: test-changed
    commands:
      - make test-changed

trigger:
  event:
  - push

---
kind: pipeline
type: exec
name: pull_request

platform:
  os: linux
  arch: amd64

steps:
#   - name: lint
#     commands:
#       - make lint
  - name: test
    commands:
      - make test

trigger:
  event:
  - pull_request