---

namespace: tesseract
name: network
version: 1.0.0
readme: README.md
authors:
  - Ben Wadsworth
description: Ansible roles for managing network configurations and services for tesseract.
license:
  - Unlicense
license_file: 'LICENSE'
repository: https://github.com/ben16w/tesseract-network
dependencies:
  "community.general": "*"
build_ignore:
  - .ansible
  - .venv
  - .drone.yml
  - .gitignore
  - requirements.txt
