---

all:
  hosts:
    192.168.56.11

  vars:
    ansible_connection: ssh
    ansible_user: "vagrant"
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: "/usr/bin/python3"

    email_username: ben16w@yahoo.com

    tesseract_username: vagrant

    tailscale_auth_key: password

    subnet: 192.168.1.0/24
    domain: gengar.lan

    proxy_ip: 192.168.56.11
    dns_ip: 192.168.56.11

    dns_records:
      onix.lan: 192.168.1.3
      tepig.lan: 192.168.1.5
      charizard.lan: 192.168.1.6
      gengar.lan: 192.168.1.8

    proxy_services:
      - subdomain: ~
        target: http://gengar.lan:81
      - subdomain: dash
        target: http://gengar.lan:81

      - subdomain: docs
        target: http://charizard.lan:8081
      - subdomain: watch
        target: http://charizard.lan:8096
        http1: true

    proxy_cloudflare_api_token: token
    proxy_acme_staging: true
