---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - proxy_services is not none
      - email_username is not none
      - domain is not none

- name: Setting architecture to amd64.
  ansible.builtin.set_fact:
    download_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: Setting architecture to arm64.
  ansible.builtin.set_fact:
    download_arch: "arm64"
  when: '"armv" in ansible_architecture or "aarch" in ansible_architecture'

- name: Increase maximum socket receive buffer.
  notify: reload sysctl
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    search_string: 'net.core.rmem_max'
    line: 'net.core.rmem_max=2500000'
    owner: root
    group: root
    mode: 0644

- name: Check if caddy is installed.
  ansible.builtin.stat:
    path: /usr/bin/caddy
  register: is_caddy_installed

- name: If caddy is installed.
  when: not is_caddy_installed.stat.exists
  block:

    - name: Ensure Go is installed.
      ansible.builtin.package:
        name: golang-go
        state: present

    - name: Download and extract xcaddy archive into tmp directory.
      ansible.builtin.get_url:
        url: "https://github.com/caddyserver/xcaddy/releases/download/v0.3.1/xcaddy_0.3.1_linux_{{ download_arch }}.deb"
        dest: /tmp/xcaddyy.deb
        owner: root
        group: root
        mode: 0644

    - name: Install a xcaddy package.
      ansible.builtin.apt:
        deb: /tmp/xcaddyy.deb

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /tmp/caddy
        state: directory
        owner: root
        group: root
        mode: 0777

    - name: Xcaddy build.
      ansible.builtin.command:
        cmd: >
          xcaddy build
          --with github.com/caddy-dns/cloudflare
          --with github.com/caddyserver/cache-handler
        creates: /tmp/caddy/caddy
        chdir: /tmp/caddy
      when: not is_caddy_installed.stat.exists

    - name: Install caddy.
      ansible.builtin.copy:
        src: /tmp/caddy/caddy
        dest: /usr/bin/caddy
        remote_src: true
        owner: root
        group: root
        mode: 0755

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /opt/caddy
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /var/log/caddy
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Template a Caddyfile
  notify: restart caddy
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: /opt/caddy/Caddyfile
    force: true
    owner: root
    group: root
    mode: 0644

- name: Putcaddy systemd file into place.
  notify: restart caddy
  ansible.builtin.template:
    src: templates/caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    force: true
    owner: root
    group: root
    mode: 0644

- name: Make sure caddy service unit is running and enabled.
  ansible.builtin.systemd:
    state: started
    name: caddy
    enabled: true
