---

- name: Restart blocky service.
  ansible.builtin.service:
    name: blocky.service
    state: restarted
  listen: restart blocky

- name: Restart systemd-resolved service.
  ansible.builtin.service:
    name: systemd-resolved.service
    state: restarted
  listen: restart systemd-resolved
