---
- name: Converge
  hosts: all
  vars:
    tesseract_hostname: "localhost"
    blocky_dns_records:
      - record: localhost
        value: 127.0.0.1
      - record: test.test
        value: 192.168.99.99
    blocky_version: "0.25"
  roles:
    - role: blocky
