---

tesseract_username: tesseract
domain: ben16w.site

email_username: ~

proxy_services: ~
#      - subdomain: example
#        target: http://gengar.lan:80
#        http1: true
#        gzip: true
proxy_cloudflare_api_token: ~
proxy_acme_staging: false
