---
- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - cloudflare_dns_api_token is not none
      - cloudflare_dns_zone is not none

- name: Create DNS records.
  community.general.cloudflare_dns:
    zone: "{{ cloudflare_dns_zone }}"
    record: "{{ item.record }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    api_token: "{{ cloudflare_dns_api_token }}"
  with_items: "{{ cloudflare_dns_records }}"
  when: cloudflare_dns_records | length > 0
