---
- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - cloudflare_dns_api_key is not none
      - cloudflare_dns_email is not none
      - cloudflare_dns_zone is not none
      - cloudflare_dns_records is not none

- name: Create DNS records.
  community.general.cloudflare_dns:
    zone: "{{ cloudflare_dns_zone }}"
    record: "{{ item.record }}}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    account_email: "{{ cloudflare_dns_email }}"
    account_api_key: "{{ cloudflare_dns_api_key }}"
  with_items: "{{ cloudflare_dns_records }}"
  when: cloudflare_dns_records | length > 0
