---

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - curl
      - tar
      - nftables
    update_cache: true

- name: Download Whalewall binary
  ansible.builtin.get_url:
    url: "https://github.com/capnspacehook/whalewall/releases/latest/download/whalewall-linux-amd64.tar.gz"
    dest: "/tmp/whalewall.tar.gz"
    mode: '0644'
    user: root
    group: root

- name: Extract Whalewall binary
  unarchive:
    src: "/tmp/whalewall.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: true
    creates: "/usr/local/bin/whalewall"

- name: Set group ownership to docker for Whalewall binary
  command: chgrp docker /usr/local/bin/whalewall

- name: Set NET_ADMIN capability for Whalewall binary
  command: setcap 'cap_net_admin=+ep' /usr/local/bin/whalewall

- name: Template Whalewall service file.
  template:
    src: whalewall.service.j2
    dest: /etc/systemd/system/whalewall.service
    mode: '0644'
    user: root
    group: root

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Whalewall service
  systemd:
    name: whalewall
    enabled: yes
    state: started
