---

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - curl
      - tar
      - nftables
    update_cache: true

- name: Download Whalewall binary
  ansible.builtin.get_url:
    url: "{{ whalewall_download_url }}"
    dest: "/tmp/whalewall.tar.gz"
    mode: '0644'
    user: root
    group: root

- name: Ensure Whalewall directory exists in opt.
  ansible.builtin.file:
    path: /opt/whalewall
    state: directory
    mode: '0755'
    user: root
    group: docker

- name: Extract Whalewall binary
  unarchive:
    src: /tmp/whalewall.tar.gz
    dest: /opt/whalewall
    remote_src: true
    creates: /opt/whalewall/whalewall

- name: Set permissions for Whalewall binary.
  ansible.builtin.file:
    src: /opt/whalewall/whalewall
    mode: '0755'
    user: root
    group: docker

- name: Set NET_ADMIN capability for Whalewall binary.
  command: setcap 'cap_net_admin=+ep' /opt/whalewall/whalewall

- name: Template Whalewall service file.
  template:
    src: whalewall.service.j2
    dest: /etc/systemd/system/whalewall.service
    mode: '0644'
    user: root
    group: root

- name: Enable and start Whalewall service.
  systemd:
    name: whalewall
    enabled: true
    state: started
