---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - firewall_rules is iterable
      - firewall_rules | length > 0

- name: Install UFW
  ansible.builtin.package:
    name: ufw
    update_cache: true

- name: Configure UFW rules.
  with_items: "{{ firewall_rules }}"
  ansible.builtin.command:
    cmd: ufw {{ item.rule }} {{ item.port }}/{{ item.proto }}

- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled
    policy: allow

- name: Set UFW to start on boot
  ansible.builtin.command:
    cmd: ufw enable
  changed_when: false
