---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - firewall_rules is iterable

- name: Install UFW
  ansible.builtin.package:
    name: ufw
    update_cache: true

- name: When firewall rules are provided, configure UFW.
  block:
    - name: Configure UFW rules.
      community.general.ufw:
        rule: "{{ item.rule | default('allow') }}"
        port: "{{ item.port | default(omit) }}"
        interface: "{{ item.interface | default(omit) }}"
        direction: "{{ item.direction | default(omit) }}"
        src: "{{ item.src | default(omit) }}"
        state: enabled
      loop: "{{ firewall_rules }}"

    - name: Set default UFW policy.
      community.general.ufw:
        policy: "{{ firewall_default_policy }}"
        state: enabled
