---

- name: Assert that all required inputs have been provided.
  ansible.builtin.assert:
    that:
      - firewall_rules is iterable
      - firewall_rules | length > 0

- name: Install UFW.
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Enable UFW.
  ansible.builtin.command:
    cmd: ufw --force enable

- name: Configure UFW rules.
  with_items: "{{ ufw_rules }}"
  ansible.builtin.command:
    cmd: ufw {{ item.rule }} {{ item.port }}/{{ item.proto }}
