---

- name: Ensure dhcpd package is installed.
  ansible.builtin.package:
    name: isc-dhcp-server
    state: present

- name: Ensure destination for dhcp file exists.
  ansible.builtin.file:
    path: /etc/dhcp/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Put the isc-dhcp-server configuration file into place.
  ansible.builtin.template:
    src: templates/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0755
  notify: restart isc-dhcp-server

- name: Replace a localhost entry.
  lineinfile:
    path: /etc/default/isc-dhcp-server
    search_string: INTERFACESv4
    line: INTERFACESv4="eth0 eth1"
    owner: root
    group: root
    mode: 0644
  notify: restart isc-dhcp-server

- name: Replace a localhost entry.
  lineinfile:
    path: /etc/default/isc-dhcp-server
    search_string: DHCPDv4_CONF
    line: DHCPDv4_CONF=/etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart isc-dhcp-server

- name: Make sure the isc-dhcp-server systemd service unit is running and enabled.
  ansible.builtin.systemd:
    state: started
    name: isc-dhcp-server
    enabled: true
