---
- name: Converge
  hosts: all
  vars_files:
    - ../../defaults/main.yml
    - ./vars.yml
  tasks:
    - name: Ensure Python3 is installed
      ansible.builtin.package:
        name: python3
        state: present

    - name: Start dummy HTTP server on port 8081 and log output
      ansible.builtin.shell:
        cmd: python3 -m http.server 8081 > /tmp/http_server_8081.log 2>&1 &
      changed_when: false

    - name: Start dummy HTTP server on port 8082 and log output
      ansible.builtin.shell:
        cmd: python3 -m http.server 8082 > /tmp/http_server_8082.log 2>&1 &
      changed_when: false
