---

- name: Ensure systemd-resolved.conf is set correctly
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#?DNS=', line: 'DNS=1.1.1.1' }
    - { regexp: '^#?DNSStubListener=', line: 'DNSStubListener=no' }
  notify: restart systemd-resolved
