---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
  - name: Check UFW firewall status.
    command: ufw status verbose
    register: ufw_status

  - name: Verify UFW firewall is active.
    assert:
      that:
        - "'Status: active' in ufw_status.stdout"
      fail_msg: "UFW firewall is not active"
      success_msg: "UFW firewall is active"

  - name: Verify UFW default policy.
    assert:
      that:
        - "'Default: {{ firewall_default_policy }} (incoming)' in ufw_status.stdout"
      fail_msg: "UFW default policy is not set to {{ firewall_default_policy }}"
      success_msg: "UFW default policy is set to {{ firewall_default_policy }}"

  - name: Verify UFW rules.
    when: firewall_rules | length > 0
    block:
      - name: Get UFW rules
        command: ufw show added
        register: ufw_rules

      - name: Verify UFW rules are configured.
        assert:
          that:
            - "'{{ item }}' in ufw_rules.stdout"
          with_items: "{{ firewall_rules }}"
          fail_msg: "UFW rule '{{ item }}' is not configured"
          success_msg: "UFW rule '{{ item }}' is configured"

          # - name: Verify UFW is working by communicating from localhost
          #   command: nc -zv localhost {{ firewall_rules[0].port }}
          #   register: ufw_communication

          # - name: Verify UFW is working
          #   assert:
          #     that:
          #       - ufw_communication.rc == 0
          #     fail_msg: "UFW is not working"
          #     success_msg: "UFW is working"