---
- name: Verify
  hosts: all
  vars:
    firewall_default_policy: "deny"
    firewall_rules:
      - rule: "allow"
        port: "80"
    testing_denied_ports:
      - 8888
  tasks:
    - name: Check UFW firewall status.
      ansible.builtin.command:
        cmd: ufw status verbose
      register: ufw_status

    - name: Verify UFW firewall is active.
      assert:
        that:
          - "'Status: active' in ufw_status.stdout"

    - name: Verify UFW default policy.
      assert:
        that:
          - "'Default: {{ firewall_default_policy }} (incoming)' in ufw_status.stdout"

    - name: Get UFW rules
      ansible.builtin.command:
        cmd: ufw show added
      register: ufw_rules

    - name: Verify UFW rules are configured.
      assert:
        that:
          - item.rule in ufw_rules.stdout
          - item.port in ufw_rules.stdout
      loop: "{{ firewall_rules }}"
