---

- name: Reload sysctl settings.
  listen: reload sysctl
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.conf
  changed_when: true

- name: Restart Tailscale.
  listen: restart tailscale
  ansible.builtin.systemd:
    state: restarted
    name: tailscaled
